# Generated by Django 5.0.4 on 2024-04-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gradvisor", "0005_rename_gpa_applicant_cgpa_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="cgpa",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="gre_score",
            field=models.IntegerField(default=260),
        ),
    ]
